name: Run Advanced Investment Alert Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # כל שעה

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies including PyTorch
        run: |
          pip install yfinance requests beautifulsoup4 feedparser python-telegram-bot transformers pandas
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

      - name: Run advanced bot script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python advanced_investment_alert.py
